config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create ]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, :scope => [:list_id]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_one_attached :photo
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      redirect_to new_list_path
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container col-6">
<h1 class="text-center">Add Bookmark</h1>
<h2 ><%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>
</h2>

<p><%= link_to lists_path do%>
  <i class="fas fa-arrow-alt-circle-left"> Back to Lists</i>
<% end %>
</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
  <div class="navbar navbar-light bg-light">
    <div class="btn btn-sm btn-outline-secondary">
      <%= link_to new_list_path do%>
        <i class="fas fa-plus btn btn-ghost">  Create a list</i>
      <% end %>
    </div>
  </div>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://media.istockphoto.com/photos/empty-red-armchairs-of-a-theater-ready-for-a-show-picture-id1295114854?b=1&k=20&m=1295114854&s=170667a&w=0&h=W9ZbN674554Jsamxo5AfoO3DrSm_7qYS1EnANgusi9o=)">
  <h1>Movie Lists</h1>
  </div>
<div class="container">
  <div class="cards">
    <% @lists.each do |list| %>
    <li class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')"><%= link_to list.name, list_path(list), class: "text-decoration-none f-light text-white"%></li>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://cdn.pixabay.com/photo/2019/04/24/21/55/cinema-4153289__340.jpg)">
</div>
  <div class="container" >
    <h1 class="text-center f-color-black" >Create New List</h1>
  </div>
  <h2 ><%= simple_form_for [@list] do |f| %>
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
  </h2>

  <p><%= link_to lists_path do%>
    <i class="fas fa-arrow-alt-circle-left"> Back to Lists</i>
  <% end %>
  </p>

app/views/lists/show.html.erb
<div class="container col-8">
  <div class="navbar navbar-light bg-light">
    <p>
      <%= link_to new_list_bookmark_path(@list) do%>
        <i class="fas fa-plus btn btn-ghost">Add Bookmark</i>
      <% end %>
    </p>

    <p>
      <%= link_to lists_path do%>
        <i class="fas fa-arrow-alt-circle-left btn btn-ghost"> Back to Lists</i>
      <% end %>
    </p>
  </div>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://pbs.twimg.com/media/ESNhDyHWsAATd_a.jpg)">
    <h1> Movie Shows here</h1>
  </div>
  <div class="cards">
  <% @list.bookmarks.each do |bookmark| %>
    <div class="card p-3" style="width: 18rem;">
      <%= image_tag bookmark.movie.poster_url %>
      <div class="card-body">
        <h5 class="card-title"><%= bookmark.movie.title %></h5>
        <p><i class="fas fa-star text-warning"></i> <%= bookmark.movie.rating %> </p>
        <p class="card-text"> <%= bookmark.movie.overview[1..70] %> </p>
      </div>
      <div class="card-body">
        <a href="#" class="card-link">Card link</a>
        <a href="#" class="card-link">Another link</a>
      </div>
    </div>
     <%end %>
  </div>
</div>